coeficiente_binomial_ejercicio/numero_combinatorio/numero_combinatorio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('numero_combinatorio_app.urls'), name='index')
]

coeficiente_binomial_ejercicio/numero_combinatorio/numero_combinatorio_app/urls.py
from django.urls import path
from . import views

app_name = 'numero_combinatorio'

urlpatterns = [
    path('', views.index, name="index"),
    path('result/', views.result, name="result"),
]

coeficiente_binomial_ejercicio/numero_combinatorio/numero_combinatorio_app/models.py
from django.db import models

# Create your models here.

coeficiente_binomial_ejercicio/numero_combinatorio/numero_combinatorio_app/views.py
from inspect import getinnerframes
from itertools import combinations
from math import comb
from django.shortcuts import render
import random

# Create your views here.

def index(request, amount_letters=4):
    if(request.POST.get('amount') != None):
        amount_letters = int(request.POST.get('amount'))
        bc = binomial_coef(amount_letters, 2)
        combinations, answer = create_combinations(amount_letters, bc)
        return render(request, 'index.html', context={'combinations':combinations, 'amount_letters':amount_letters, 'bc':bc, 'correct_answer':answer})
    bc = binomial_coef(amount_letters, 2)
    combinations, answer = create_combinations(amount_letters, bc)
    return render(request, 'index.html', context={'combinations':combinations, 'amount_letters':amount_letters, 'bc':bc, 'correct_answer':answer})

def result(request):
    correct_ans = request.POST.get('correct_ans', 'default_value')
    ans_attempt = request.POST.get('answer_attempt', 'default_value')
    if(int(correct_ans) == int(ans_attempt)):
        return render(request, 'result.html', context={'state':'correct', 'message':'Felicidades, respuesta correcta!', 'image': get_image(True)}) 
    return render(request, 'result.html', context={'state':'incorrect', 'message': 'Respuesta incorrecta, intente denuevo :(', 'image': get_image(False)}) 
    

#functions
def get_image(answer:bool):
    images = {
        'feliz': ['alpaca','castor','chica'],
        'triste': ['duende','luis','mario']
    }
    if answer:
        return "feliz/" + images['feliz'][random.randint(0, len(images['feliz']) - 1)] + "_feliz.jpg"
    return "triste/" + images['triste'][random.randint(0, len(images['triste']) - 1)] + "_triste.jpg"
    

def binomial_coef(n:int, k:int):
    if(k == 0 or n == k):
        return 1
    return binomial_coef(n - 1, k - 1) + binomial_coef(n - 1, k)
 
def create_combinations(amount_letters:int, bc:int):
    letters:list = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
    r = random.randint(0, bc)
    letters = letters[r:r +amount_letters]
    combinations:list = []
    combinations_inverse:list = []

    for a1 in letters:
        for a2 in letters:
            if(a1 == a2): 
                continue
            if([a1, a2] in combinations or [a2, a1] in combinations_inverse): 
                continue
            combinations.append([a1,a2])
            combinations_inverse.append([a2,a1])

    r = random.randint(0, bc)
    return combinations[r: r + bc], random.randint(0, bc - 1)





    

coeficiente_binomial_ejercicio/numero_combinatorio/numero_combinatorio_app/templates/index.html
{% load static %}
<!--DOCTYPE html-->
<html lang="en">
	<head>
		<title>Juego de combinaciones</title>
		<link rel="stylesheet" href="{% static 'style.css' %}" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<form action="{% url 'numero_combinatorio:index' %}" method="POST" id="amount_form">
			{% csrf_token %}
			<label>Ingrese la cantidad de digitos con las que jugar <b>Rango (2-5)</b>:</label><br><br>
			<input type="number" id="amount_inp" min=2 max=5 name="amount" value={{amount_letters}} />
			<button id="amount_btn">Cargar nueva partida</button>
			<p>Existen {{bc}} parejas distíntas para {{amount_letters}} dígitos.</p>
		</form>
		<div id="container">
			<form id="result_form" action="{% url 'numero_combinatorio:result' %}" method="POST">
			{% csrf_token %}
			<input type='hidden' id="correct_ans" name="correct_ans" value="{{correct_answer}}" />
			{% for el in combinations %}
			<div class="result_radio_div"><label>{{el}}<input type="radio" required name="answer_attempt" class="result_radio" /></label></div>
			{% endfor %}
			<button>Answer</button>
			</form>
		</div>
		<script src="{% static 'main.js' %}"></script>
	</body>
</html>

coeficiente_binomial_ejercicio/numero_combinatorio/numero_combinatorio_app/templates/result.html
{% load static %}
<!--DOCTYPE html-->
<html lang="en">
	<head>
		<title>Juego de combinaciones</title>
		<link rel="stylesheet" href="{% static 'style.css' %}" />
		<link rel="stylesheet" href="{% static 'result.css' %}" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<div id="{{state}}" class="result_container">
			<h1>{{message}}</h1>
			<img src="{% static image %}" alt="image"/>
			<form method="POST" action="{% url 'numero_combinatorio:index' %}">
				{% csrf_token %}
				<button>Voler a jugar</button>
			</form>
		</div>
	</body>
	<script src="{% static 'result.js' %}"></script>
</html>